version: "3"

services:
  postgresqldb:
    container_name: pgdb
    hostname: pgdb
    image: postgres:14.1-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: aurigabot
    ports:
      - "5432:5432"
    volumes:
      - postgresqldb-data:/var/lib/postgresql/data
    networks:
      - mynet

  aurigabot:
    container_name: aurigabot
    image: "surabhidocker28/aurigabot:v2"
    restart: always
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 60s
      timeout: 10s
      retries: 5
    ports:
      - "0.0.0.0:8080:8080"
    networks:
      - mynet

volumes:
  postgresqldb-data:

networks:
  mynet:
    driver: bridge
