version: "3"

services:
  # Kafka
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - mynet
    ports:
      - "2181:2181"
  
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    networks:
      - mynet
    ports:
      - "9094:9094"
    environment:
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://dev.uci.samagra.io:9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:SASL_PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      KAFKA_LOG_DIRS: ./data00/kafka-logs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./etc/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
      - ./data00/kafka:/kafka
      - ./kafka-data:/var/lib/kafka:Z
    links:
      - zookeeper

  schema-registry:
    image: confluentinc/cp-schema-registry
    restart: on-failure
    networks:
      - mynet
    depends_on:
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:9092'
      SCHEMA_REGISTRY_HOST_NAME: 'schema-registry'
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:8085'
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: 'INFO'

  connect:
    image: confluentinc/cp-kafka-connect
    depends_on:
      - kafka
      - schema-registry
    networks:
      - mynet
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONNECT_REST_PORT: '8083'
      CONNECT_REST_LISTENERS: 'http://0.0.0.0:8083'
      CONNECT_REST_ADVERTISED_HOST_NAME: 'connect'
      CONNECT_CONFIG_STORAGE_TOPIC: '__connect-config'
      CONNECT_OFFSET_STORAGE_TOPIC: '__connect-offsets'
      CONNECT_STATUS_STORAGE_TOPIC: '__connect-status'
      CONNECT_GROUP_ID: 'kafka-connect'
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: 'true'
      CONNECT_KEY_CONVERTER: 'io.confluent.connect.avro.AvroConverter'
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8085'
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: 'true'
      CONNECT_VALUE_CONVERTER: 'io.confluent.connect.avro.AvroConverter'
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8085'
      CONNECT_INTERNAL_KEY_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_INTERNAL_VALUE_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: '1'
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: '1'
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: '1'
      CONNECT_PLUGIN_PATH: ' /usr/share/java/'

  akhq:
    image: tchiotludo/akhq
    networks:
      - mynet
    ports:
     - "18080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          security:
            basic-auth:
              - username: admin
                password: d49745a74edfd20705ccaa277209db554b6b0d78c20780a4facf87e88aee78c0
                groups: 
                  - admin
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
              schema-registry:
                url: "http://schema-registry:8085"
              connect:
                - name: "connect"
                  url: "http://connect:8083"

  postgresqldb:
    container_name: pgdb
    hostname: pgdb
    image: postgres:14.1-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: aurigabot
    ports:
      - "5432:5432"
    volumes:
      - postgresqldb-data:/var/lib/postgresql/data
    networks:
      - mynet

  aurigabot:
    container_name: aurigabot
    image: "surabhidocker28/aurigabot:v5"
    restart: always
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 60s
      timeout: 10s
      retries: 5
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - mynet

volumes:
  postgresqldb-data:

networks:
  mynet:
    driver: bridge
