version: "3"

services:
  # Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - mynet
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    networks:
      - mynet
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgresqldb:
    container_name: pgdb
    hostname: pgdb
    image: postgres:14.1-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: aurigabot
    ports:
      - "5432:5432"
    volumes:
      - postgresqldb-data:/var/lib/postgresql/data
    networks:
      - mynet

  aurigabot:
    container_name: aurigabot
    image: "surabhidocker28/aurigabot:v5"
    restart: always
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 60s
      timeout: 10s
      retries: 5
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - mynet

volumes:
  postgresqldb-data:

networks:
  mynet:
    driver: bridge
