insert into flow (command_type, question, index, payload, validation) values ('/events', 'Please choose any of the operations', 0, '{"question": "Please choose any of the operations", "questionType": "TEXT", "choices": null, "mediaUrl": null}', '{ "fieldType": "TEXT", "textValidationConfig": { "max": "10"}}');

insert into flow (command_type, question, index, payload, validation) values ('/listevents', 'Please enter start date for events', 0, '{"question": "Please enter start date for events", "questionType": "DATE", "choices": null, "mediaUrl": null}', '{ "fieldType": "DATE", "dateValidationConfig": { "format": "dd-MM-yyyy" }}');
insert into flow (command_type, question, index, payload, validation) values ('/listevents', 'Please enter end date for events', 1, '{"question": "Please enter end date for events", "questionType": "DATE", "choices": null, "mediaUrl": null}', '{ "fieldType": "DATE", "dateValidationConfig": { "format": "dd-MM-yyyy" }}');

insert into flow (command_type, question, index, payload, validation) values ('/createevents', 'Please enter summary for new event', 0, '{"question": "Please enter summary for new event", "questionType": "TEXT", "choices": null, "mediaUrl": null}', '{ "fieldType": "TEXT", "textValidationConfig": { "max": "100", "min": "10" }}');
insert into flow (command_type, question, index, payload, validation) values ('/createevents', 'Please enter location for new event', 1, '{"question": "Please enter location for new event", "questionType": "TEXT", "choices": null, "mediaUrl": null}', '{ "fieldType": "TEXT", "textValidationConfig": { "max": "50", "min": "10" }}');
insert into flow (command_type, question, index, payload, validation) values ('/createevents', 'Please enter description for new event', 2, '{"question": "Please enter description for new event", "questionType": "TEXT", "choices": null, "mediaUrl": null}', '{ "fieldType": "TEXT", "textValidationConfig": { "min": "10" }}');
insert into flow (command_type, question, index, payload, validation) values ('/createevents', 'Please enter start date for new event', 3, '{"question": "Please enter start date for new event", "questionType": "DATE", "choices": null, "mediaUrl": null}', '{ "fieldType": "DATE", "dateValidationConfig": { "format": "dd-MM-yyyy" }}');
insert into flow (command_type, question, index, payload, validation) values ('/createevents', 'Please enter end date for new event', 4, '{"question": "Please enter end date for new event", "questionType": "DATE", "choices": null, "mediaUrl": null}', '{ "fieldType": "DATE", "dateValidationConfig": { "format": "dd-MM-yyyy" }}');
insert into flow (command_type, question, index, payload, validation) values ('/createevents', 'Please enter timezone for new event', 5, '{"question": "Please enter timezone for new event", "questionType": "TEXT", "choices": null, "mediaUrl": null}', '{ "fieldType": "TEXT", "textValidationConfig": { "min": "5" }}');